import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navibar from "@/components/Navibar";
import QueryClientProviderWrapper from "@/components/QueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen min-h-0 flex-row overflow-hidden bg-[var(--chat-main-bg)]`}
      >
        <ClerkProvider>
          <QueryClientProviderWrapper>
            <aside className="h-full w-[260px] shrink-0">
              <Navibar />
            </aside>
            <main className="h-full min-h-0 min-w-0 flex-1">{children}</main>
          </QueryClientProviderWrapper>
        </ClerkProvider>
      </body>
    </html>
  );
}
